### ISSUE TITLE
Design SQL structure

### ISSUE THREAD

**Issue by jrec15** [rocketpastsix/transparentcoffee#10]
Should be based on the following:
![screen shot 2015-05-16 at 1 24 56 pm](https://cloud.githubusercontent.com/assets/7320557/7667238/111c676e-fbcf-11e4-82e0-15b722000268.png)
![screen shot 2015-05-16 at 1 25 03 pm](https://cloud.githubusercontent.com/assets/7320557/7667239/124c3858-fbcf-11e4-8645-a856175edd22.png)
Should talk about if the proof document goes in the database? Not really sure honestly

**Comment by matthewtrask** [comment]
taken care of, but please double check me. I added comments to make it clear. I think that both tables will mirror each other. I designed it so that theres a pending table, after the roaster applies, and an approved table. The only thing Im unsure of is should we create a relationship table for images. I have it so that the image is apart of the main tables, but we can create a separate table for images alone.
